In [1]:
import os
import pickle
import pandas as pd
import numpy as np
import random

In [2]:
import tensorflow as tf
from tensorflow.python.ops.gen_math_ops import Exp

from src.model.embedding import MovieGenreEmbedding, UserMovieEmbedding

In [3]:
users_num = 944
items_num = 1683
embedding_dim = 50

In [4]:
embedding_network = UserMovieEmbedding(
    users_num, items_num, embedding_dim
)
embedding_network([np.zeros((1,)), np.zeros((1,))])

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.49994957]], dtype=float32)>

In [5]:
embedding_network.load_weights("model/movie_lens_100k/user_movie_at_once.h5")

In [6]:
user_eb = embedding_network.get_layer("user_embedding")(
    np.array(336)
)
items_eb = embedding_network.get_layer("movie_embedding")(
    np.array([66, 108, 577, 619, 13])
)

In [7]:
user_eb

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([-0.15094106,  0.01772034,  0.03551648, -0.3886132 ,  0.23306383,
        0.1586119 ,  0.1727339 ,  0.0303234 , -0.24824218, -0.0311781 ,
        0.49713385, -0.0460876 ,  0.0114561 ,  0.34791   ,  0.3732463 ,
        0.13759081,  0.19672911, -0.6011166 , -0.27336878, -0.00823429,
       -0.4246496 ,  0.34664536,  0.6763402 , -0.07966334, -0.09961307,
        0.19077118, -0.24282195,  0.75532174,  0.1167687 ,  0.10710243,
        0.36551002,  0.51719993, -0.2879935 , -0.05009588,  0.47714666,
        0.02968461,  0.14070405, -0.1736734 , -0.39514434, -0.32729068,
       -0.13292897, -0.05734332, -0.11795778,  0.2782598 ,  0.21425496,
       -0.15607196,  0.13125156, -0.5578403 , -0.33750695, -0.2422642 ],
      dtype=float32)>

In [8]:
np.expand_dims(user_eb, axis=0)

array([[-0.15094106,  0.01772034,  0.03551648, -0.3886132 ,  0.23306383,
         0.1586119 ,  0.1727339 ,  0.0303234 , -0.24824218, -0.0311781 ,
         0.49713385, -0.0460876 ,  0.0114561 ,  0.34791   ,  0.3732463 ,
         0.13759081,  0.19672911, -0.6011166 , -0.27336878, -0.00823429,
        -0.4246496 ,  0.34664536,  0.6763402 , -0.07966334, -0.09961307,
         0.19077118, -0.24282195,  0.75532174,  0.1167687 ,  0.10710243,
         0.36551002,  0.51719993, -0.2879935 , -0.05009588,  0.47714666,
         0.02968461,  0.14070405, -0.1736734 , -0.39514434, -0.32729068,
        -0.13292897, -0.05734332, -0.11795778,  0.2782598 ,  0.21425496,
        -0.15607196,  0.13125156, -0.5578403 , -0.33750695, -0.2422642 ]],
      dtype=float32)

In [10]:
items_eb

<tf.Tensor: shape=(5, 50), dtype=float32, numpy=
array([[ 2.72305720e-02, -1.66319922e-01,  2.69393861e-01,
         5.02112173e-02,  4.31551635e-01,  1.37414947e-01,
        -2.27460578e-01, -2.97179878e-01,  5.51800430e-01,
         8.32657292e-02, -1.48278456e-02,  3.34258258e-01,
         1.40118394e-02, -5.86407632e-02, -5.17630100e-01,
        -1.63598046e-01,  1.59545347e-01,  4.44754750e-01,
         7.20159709e-02, -2.74963647e-01,  6.77966848e-02,
         6.16299510e-01, -1.10355847e-01,  2.65106708e-01,
        -5.97724020e-02,  6.83196262e-02, -1.87432796e-01,
        -1.69355646e-02,  3.93377356e-02,  4.93071854e-01,
         1.19172089e-01,  1.95559725e-01,  2.07346395e-01,
         1.64533168e-01, -3.64328027e-02,  3.12206805e-01,
        -4.61524576e-01,  3.79035801e-01, -3.39848995e-01,
        -1.21723652e-01,  2.35487625e-01,  3.08316708e-01,
        -7.39503086e-01, -2.90658206e-01,  2.85889477e-01,
         1.14647910e-01, -3.24365675e-01,  8.44068006e-02,
       

In [11]:
np.expand_dims(items_eb, axis=0)

array([[[ 2.72305720e-02, -1.66319922e-01,  2.69393861e-01,
          5.02112173e-02,  4.31551635e-01,  1.37414947e-01,
         -2.27460578e-01, -2.97179878e-01,  5.51800430e-01,
          8.32657292e-02, -1.48278456e-02,  3.34258258e-01,
          1.40118394e-02, -5.86407632e-02, -5.17630100e-01,
         -1.63598046e-01,  1.59545347e-01,  4.44754750e-01,
          7.20159709e-02, -2.74963647e-01,  6.77966848e-02,
          6.16299510e-01, -1.10355847e-01,  2.65106708e-01,
         -5.97724020e-02,  6.83196262e-02, -1.87432796e-01,
         -1.69355646e-02,  3.93377356e-02,  4.93071854e-01,
          1.19172089e-01,  1.95559725e-01,  2.07346395e-01,
          1.64533168e-01, -3.64328027e-02,  3.12206805e-01,
         -4.61524576e-01,  3.79035801e-01, -3.39848995e-01,
         -1.21723652e-01,  2.35487625e-01,  3.08316708e-01,
         -7.39503086e-01, -2.90658206e-01,  2.85889477e-01,
          1.14647910e-01, -3.24365675e-01,  8.44068006e-02,
          1.71938110e-02,  5.37552834e-0

In [12]:
with open("data/ml-100k/movies_groups.pkl", "rb") as pkl_file:
    movies_group = pickle.load(pkl_file)

# movies_group

In [62]:
movies_group[1684]

KeyError: 1684

In [13]:
groups_eb = []
for items in [66, 108, 577, 619, 13]:
    groups_eb.append(embedding_network.get_layer("movie_embedding")(
        np.array(
            [
                k
                for k, v in movies_group.items()
                if v == movies_group[items]
            ]
        )
    ))

In [14]:
output = []
for group in groups_eb:
    output.append(tf.reduce_mean(group / embedding_dim, axis=0))
output = tf.stack(output)
output

<tf.Tensor: shape=(5, 50), dtype=float32, numpy=
array([[ 1.92852155e-03,  4.31409106e-03, -2.67175445e-03,
        -3.92265664e-03,  4.35244665e-03, -1.82889134e-03,
        -6.49927242e-04,  2.00836267e-03,  3.64360094e-05,
        -2.01072032e-03,  3.42264585e-03,  1.87992549e-03,
         2.09584436e-03, -2.10003648e-03, -2.77006510e-03,
         2.01207795e-03,  2.00468837e-03,  1.01184116e-04,
        -3.10625229e-03,  9.54065472e-05,  7.92386054e-05,
         3.18139512e-03,  3.78655130e-03, -1.10190618e-03,
         1.73456792e-03,  1.94462726e-03,  2.92282901e-04,
         3.30315810e-03, -2.99599161e-03,  5.96550386e-03,
         3.44088208e-03, -4.52188979e-04,  1.78250833e-03,
        -1.18567771e-03,  2.56874086e-03,  3.82470811e-04,
        -5.73066482e-03, -6.18007616e-04, -4.60051728e-04,
        -1.10301643e-03,  4.08684043e-03, -7.08049221e-04,
         3.34071834e-03,  4.16541519e-03,  1.38657808e-03,
         2.75477360e-05,  2.24557566e-03, -1.93972723e-03,
       

In [15]:
out = tf.keras.layers.Add()([np.expand_dims(items_eb, axis=0), np.expand_dims(output, axis=0)])
out

<tf.Tensor: shape=(1, 5, 50), dtype=float32, numpy=
array([[[ 0.02915909, -0.16200583,  0.2667221 ,  0.04628856,
          0.4359041 ,  0.13558605, -0.2281105 , -0.29517153,
          0.55183685,  0.08125501, -0.0114052 ,  0.3361382 ,
          0.01610768, -0.0607408 , -0.52040017, -0.16158597,
          0.16155003,  0.44485593,  0.06890972, -0.27486825,
          0.06787592,  0.6194809 , -0.1065693 ,  0.2640048 ,
         -0.05803783,  0.07026425, -0.18714051, -0.01363241,
          0.03634175,  0.49903736,  0.12261297,  0.19510753,
          0.2091289 ,  0.1633475 , -0.03386406,  0.3125893 ,
         -0.46725523,  0.3784178 , -0.34030905, -0.12282667,
          0.23957446,  0.30760866, -0.73616236, -0.2864928 ,
          0.28727606,  0.11467545, -0.3221201 ,  0.08246707,
          0.01794704,  0.04982436],
        [ 0.39232984,  0.15701278,  0.10437169, -0.11275486,
         -0.04977163, -0.22818877, -0.2414495 ,  0.2054027 ,
          0.03646794, -0.135083  ,  0.65663517,  0.2222365

In [16]:
V = tf.keras.layers.Dense(1)

In [19]:
attention_hidden_layer = (tf.nn.relu(out))

# score shape == (batch_size, 64, 1)
# This gives you an unnormalized score for each image feature.
score = V(attention_hidden_layer)

# attention_weights shape == (batch_size, 64, 1)
attention_weights = tf.nn.softmax(score, axis=1)

# context_vector shape after sum == (batch_size, hidden_size)
context_vector = attention_weights * out
context_vector = tf.reduce_sum(context_vector, axis=1)

In [20]:
context_vector

<tf.Tensor: shape=(1, 5, 50), dtype=float32, numpy=
array([[[ 0.00845566, -0.04697906,  0.07734509,  0.01342293,
          0.12640512,  0.03931776, -0.06614835, -0.08559495,
          0.16002373,  0.02356263, -0.00330732,  0.09747462,
          0.00467097, -0.01761385, -0.1509076 , -0.04685731,
          0.04684689,  0.129001  ,  0.0199827 , -0.07970733,
          0.01968292,  0.17963941, -0.03090337,  0.07655711,
         -0.01683003,  0.02037549, -0.05426771, -0.00395318,
          0.01053852,  0.14471273,  0.03555577,  0.05657802,
          0.06064399,  0.04736812, -0.00982003,  0.09064582,
         -0.13549644,  0.10973502, -0.0986841 , -0.03561774,
          0.06947271,  0.08920152, -0.21347514, -0.08307827,
          0.0833054 ,  0.03325402, -0.09340961,  0.02391411,
          0.00520435,  0.01444826],
        [ 0.05742378,  0.02298134,  0.01527647, -0.01650349,
         -0.00728488, -0.03339909, -0.03534001,  0.03006399,
          0.00533767, -0.01977157,  0.09610911,  0.0325278

In [27]:
ups = tf.keras.layers.Attention()([out, out])

In [53]:
fs = tf.keras.layers.Dense(50, activation="relu")(np.expand_dims([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], axis=0))


In [56]:
tf.keras.layers.Concatenate(axis=1)([ups, np.expand_dims(fs, axis=0)])

<tf.Tensor: shape=(1, 6, 50), dtype=float32, numpy=
array([[[ 6.79050907e-02, -1.31176546e-01,  2.23121732e-01,
          3.73073481e-02,  3.82695585e-01,  9.21796784e-02,
         -1.92230210e-01, -2.62609780e-01,  4.79796112e-01,
          6.04564920e-02,  2.63225846e-02,  2.96149880e-01,
          2.47210097e-02, -7.41823316e-02, -4.38482553e-01,
         -1.54310524e-01,  1.40685916e-01,  3.99510384e-01,
          7.82807320e-02, -2.56529599e-01,  9.13827866e-02,
          5.41257858e-01, -8.36810172e-02,  2.17564091e-01,
         -5.70193827e-02,  1.24722667e-01, -1.34070486e-01,
         -9.86521970e-03,  1.21522713e-02,  5.19852281e-01,
          1.41433954e-01,  1.26994357e-01,  2.20435172e-01,
          1.58854857e-01, -2.96318363e-02,  2.99612373e-01,
         -4.27631408e-01,  3.38095874e-01, -3.19564462e-01,
         -1.18955374e-01,  2.55485833e-01,  2.64845073e-01,
         -6.24565303e-01, -2.34847769e-01,  2.44670421e-01,
          1.10828593e-01, -2.93775976e-01,  4.72